List classData=[
    {
        "keming":"商务英语听力Ⅰ",
        "zhouji":"周一",
        "jijie":"1,2",
        "kaishi":"2",
        "jieshu":"5",
        "laoshi":"王璐瑶",
        "didian":"通方楼-B411"
    },
    {
        "keming":"商务英语听力Ⅰ",
        "zhouji":"周一",
        "jijie":"1,2",
        "kaishi":"7",
        "jieshu":"17",
        "laoshi":"王璐瑶",
        "didian":"通方楼-B411"
    },
    {
        "keming":"综合商务英语Ⅰ",
        "zhouji":"周二",
        "jijie":"1,2",
        "kaishi":"2",
        "jieshu":"17",
        "laoshi":"赵美云",
        "didian":"通方楼-A101"
    },
    {
        "keming":"英语口语Ⅰ",
        "zhouji":"周三",
        "jijie":"1,2",
        "kaishi":"2",
        "jieshu":"17",
        "laoshi":"CHRIS",
        "didian":"通方楼-C311"
    },
    {
        "keming":"综合商务英语Ⅰ",
        "zhouji":"周四",
        "jijie":"1,2",
        "kaishi":"2",
        "jieshu":"17",
        "laoshi":"赵美云",
        "didian":"通方楼-A404"
    },
    {
        "keming":"综合商务英语Ⅰ",
        "zhouji":"周五",
        "jijie":"1,2",
        "kaishi":"2",
        "jieshu":"16",
        "laoshi":"赵美云",
        "didian":"通方楼-B109"
    },
    {
        "keming":"商务英语阅读Ⅰ",
        "zhouji":"周三",
        "jijie":"3,4",
        "kaishi":"15",
        "jieshu":"15",
        "laoshi":"王瑞霞",
        "didian":"思源楼-334"
    },
    {
        "keming":"大学计算机基础",
        "zhouji":"周五",
        "jijie":"3,4",
        "kaishi":"2",
        "jieshu":"13",
        "laoshi":"王兰",
        "didian":"思源楼-324"
    },
    {
        "keming":"商务英语阅读Ⅰ",
        "zhouji":"周一",
        "jijie":"5,6",
        "kaishi":"3",
        "jieshu":"14",
        "laoshi":"王瑞霞",
        "didian":"思源楼-337"
    },
    {
        "keming":"商务英语阅读Ⅰ",
        "zhouji":"周一",
        "jijie":"5,6",
        "kaishi":"16",
        "jieshu":"17",
        "laoshi":"王瑞霞",
        "didian":"思源楼-337"
    },
    {
        "keming":"高等数学(A)",
        "zhouji":"周二",
        "jijie":"5,6",
        "kaishi":"2",
        "jieshu":"17",
        "laoshi":"刘先鹏",
        "didian":"通方楼-B406"
    },
    {
        "keming":"大学计算机基础",
        "zhouji":"周三",
        "jijie":"5,6",
        "kaishi":"2",
        "jieshu":"13",
        "laoshi":"王兰",
        "didian":"知行楼-A401"
    },
    {
        "keming":"高等数学(A)",
        "zhouji":"周四",
        "jijie":"5,6",
        "kaishi":"2",
        "jieshu":"17",
        "laoshi":"刘先鹏",
        "didian":"通方楼-C113-114"
    },
    {
        "keming":"商务英语听力Ⅰ",
        "zhouji":"周五",
        "jijie":"5,6",
        "kaishi":"3",
        "jieshu":"3",
        "laoshi":"王璐瑶",
        "didian":"通方楼-B109"
    },
    {
        "keming":"英语语音",
        "zhouji":"周二",
        "jijie":"7,8",
        "kaishi":"2",
        "jieshu":"17",
        "laoshi":"胡月明",
        "didian":"通方楼-C310"
    },
    {
        "keming":"体育Ⅰ-啦啦操",
        "zhouji":"周三",
        "jijie":"7,8",
        "kaishi":"2",
        "jieshu":"17",
        "laoshi":"白迎秋",
        "didian":"操场"
    },
    {
        "keming":"商务英语阅读Ⅰ",
        "zhouji":"周一",
        "jijie":"9,10",
        "kaishi":"7",
        "jieshu":"7",
        "laoshi":"王瑞霞",
        "didian":"通方楼-B108"
    },
    {
        "keming":"思想道德修养与法律基础",
        "zhouji":"周三",
        "jijie":"9,10",
        "kaishi":"2",
        "jieshu":"17",
        "laoshi":"牛晓靖",
        "didian":"思源楼-121"
    }
];